### ISSUE TITLE
Is Character a Vowel Program

### ISSUE THREAD

**Issue by IMACULGY** [IMACULGY/CPPExamples#18]
Write a value-returning function, isVowel, that returns the value true if a
given character is a vowel and otherwise returns false.

You may name the program as you please, for example, "VowelChecker.cpp"

Please make sure the program compiles and runs as it should!

[CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by mpelu** [comment]
I'll be working on this

**Comment by IMACULGY** [comment]
Go ahead
