### ISSUE TITLE
Modify README.md

### ISSUE THREAD

**Issue by IMACULGY** [IMACULGY/CPPExamples#3]
Task: Update the README.md file to include a definition of C++, including its history and origins. Include this information directly before the line stating "Contributions are welcome." You may use outside sources for this, such as Wikipedia, but do cite the sources you use.

P.S. If you see any grammar issues inside readme, you are more than welcome to fix those as well!

[CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by Mr-emeka** [comment]
would lie to do this.

**Comment by IMACULGY** [comment]
go ahead :)
