### ISSUE TITLE
Reverse digits of an integer

### ISSUE THREAD

**Issue by IMACULGY** [IMACULGY/CPPExamples#4]
Write a function, reverseDigit, that takes an integer as a parameter and returns the number with its digits reversed. For example, the value of reverseDigit(12345) is 54321; the value of reverseDigit(5600) is 65; the value of reverseDigit(7008) is 8007; and the value of reverseDigit(-532) is -235.

You may name the program as you please, for example, "DigitReverser.cpp"

Please make sure the program compiles and runs as it should!

[CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by scavenger29** [comment]
Are there constraints on how large the number can be?

**Comment by IMACULGY** [comment]
The method you use should work regardless of the number of digits, but if it is too much of a problem, assume a maximum of 10 digits, + or -.

**Comment by scavenger29** [comment]
#9 created a PR
